apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-test
  namespace: default
  labels:
    app: proxy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-test
  template:
    metadata:
      labels:
        app: proxy-test
        environment: test
    spec:
      containers:
      - name: client
        image: elcolio/net-snmp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300M
          limits:
            cpu: 100m
            memory: 400M
      - name: proxy-sidecar
        image: host.minikube.internal/proxy:1
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
          - name: SERVER_ADDRESS
            value: "192.168.0.112:11111"
          - name: PROXY_MODE
            value: sidecar
          - name: PROXY_INTERCEPT_PORT_RANGE
            value: 161
        resources:
          requests:
            cpu: 100m
            memory: 300M
          limits:
            cpu: 100m
            memory: 400M

